### PR TITLE
Implement configurable security options for Kafka producer

### PR DESCRIPTION
**Pull request by johnny2565**
Please Help Review My PR
KAFKA_SASL_USERNAME = test,
KAFKA_SASL_PASSWORD = test-password,
KAFKA_SECURITY_PROTOCOL = Plaintext,
KAFKA_TOPIC = registrationEmailAlert,
KAFKA_ENABLE_AUTO_COMMIT = true,
MESSAGE_BOKER_BOOSTRAP_SERVERS = 127.0.0.1:9092,

### CODE REVIEW

**Review by giftedGeorge — DISMISSED** [review]
Looks Solid

**Comment by dabensymon** [comment]
> Looks Solid

Needs config values list

**Review by M-Jhay — APPROVED** [review]
Looks good. Please provide the newly added configuration values.

**Review by M-Jhay — APPROVED** [review]
Nice

**Review by dabensymon — APPROVED** [review]

**Pull request merged**
